# Generated by Django 3.0 on 2020-02-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_store_items_description'),
        ('signup', '0002_auto_20200211_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('ownerEmail', models.EmailField(max_length=50)),
                ('price', models.IntegerField()),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.SignUser')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Store_items')),
            ],
            options={
                'db_table': 'OrderItems',
            },
        ),
    ]
