# Generated by Django 3.0 on 2020-02-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200225_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='buyerId',
            field=models.IntegerField(max_length=30),
        ),
    ]
